server:
   port: 9090
   
spring:
    application:
        name: user-management-gateway
        
    cloud :    
        gateway:
           enabled: true
           routes:
           - id: contact_service
             uri: http://localhost:8181/
             predicates:
              - Path=/contact/**   
              
           - id: user_service
             uri: http://localhost:8186/
             predicates:
              - Path=/user/**   
              
           - id: user_management_service
             uri: lb://user-management-service/
             predicates:
              - Path=/management/**     
              
eureka:
  client: 
      register-with-eureka: true
      service-url:
          defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}